# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocknumber', models.CharField(max_length=64, verbose_name='股票编号')),
                ('company_name', models.CharField(max_length=64, verbose_name='公司名')),
                ('industry', models.CharField(max_length=64, verbose_name='细分行业')),
                ('area', models.CharField(max_length=64, verbose_name='地区')),
                ('pe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市盈率')),
                ('outstanding', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='流通股本')),
                ('totals', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总股本')),
                ('totalAssets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总资产')),
                ('liquidAssets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='流通资产')),
                ('fixedAssets', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='固定资产')),
                ('reserved', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='公积金')),
                ('reservedPerShare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每股公积金')),
                ('esp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每股收益')),
                ('bvps', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='每股净资')),
                ('pb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市净率')),
                ('timeToMarket', models.DateTimeField(verbose_name='上市日期')),
            ],
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('link', models.URLField(verbose_name='链接')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
        ),
    ]
