# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-30 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '股票', 'verbose_name_plural': '股票'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(max_length=64, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(max_length=64, null=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '金融类'), (2, '重工业'), (3, '生物制药'), (4, '建筑施工'), (5, '电气设备'), (6, '软件服务'), (7, '专用机械'), (8, '化工原料')], default=0, verbose_name='细分行业'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stocknumber',
            field=models.CharField(max_length=64, null=True, verbose_name='股票编号'),
        ),
    ]
