# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-30 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20190430_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocknews',
            options={'verbose_name': '股票资讯', 'verbose_name_plural': '股票资讯'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='stocknumber',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=64, null=True, verbose_name='细分行业'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='timeToMarket',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上市日期'),
        ),
    ]
