# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-30 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20190430_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='company_name',
            new_name='name',
        ),
    ]
