# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-30 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190430_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='bvps',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='每股净资'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='esp',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='每股收益'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='fixedAssets',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='固定资产'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='liquidAssets',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='流通资产'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='outstanding',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='流通股本'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pb',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='市净率'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pe',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='市盈率'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reserved',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='公积金'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='reservedPerShare',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='每股公积金'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totalAssets',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='总资产'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='totals',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='总股本'),
        ),
    ]
