# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOSStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '卖家'), (1, '买家')], verbose_name='角色')),
                ('amount', models.IntegerField(verbose_name='操作数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '挂单',
                'verbose_name_plural': '挂单',
            },
        ),
        migrations.CreateModel(
            name='DealStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealtime', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('stock', models.CharField(max_length=64, verbose_name='股票编号')),
                ('amount', models.IntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买总价')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
            },
        ),
    ]
