# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-29 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOSStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(0, '卖家'), (1, '买家')], verbose_name='角色')),
                ('amount', models.IntegerField(verbose_name='操作数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总价')),
                ('datetime', models.DateTimeField(verbose_name='日期')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock', verbose_name='股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo', verbose_name='操作用户')),
            ],
        ),
        migrations.CreateModel(
            name='DealStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealtime', models.DateTimeField(verbose_name='交易时间')),
                ('stock', models.CharField(max_length=64, verbose_name='股票编号')),
                ('amount', models.IntegerField(verbose_name='购买数量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买总价')),
                ('buser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='userinfo.UserInfo')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='userinfo.UserInfo')),
            ],
        ),
    ]
