# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='广告名')),
                ('ad_img', models.ImageField(upload_to='static/ads', verbose_name='图片路径')),
                ('ad_link', models.URLField(verbose_name='广告链接')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '广告',
                'verbose_name_plural': '广告',
            },
        ),
    ]
