# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-30 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adlink',
            options={'verbose_name': '广告', 'verbose_name_plural': '广告'},
        ),
    ]
